import turtle,sys,math
n = int(sys.argv[1])
turtle.speed(0)
def squares(n,length=50):
    if n == 1:
        turtle.left(180)
        turtle.forward(length/2)
        turtle.left(90)
        turtle.forward(length/2)
        turtle.left(90)
        turtle.begin_fill()
        for i in range(4):
            turtle.forward(length)
            turtle.left(90)
        turtle.end_fill()
        turtle.forward(length/2)
        turtle.left(90)
        turtle.forward(length/2)
        turtle.right(90)
    else:
        squares(n-1,length/2)
        turtle.left(45)
        turtle.forward(2*length*math.sqrt(2)/3)
        turtle.right(45)
        squares(n-1,length/2)
        turtle.left(45)
        turtle.backward(length*math.sqrt(2))
        turtle.right(45)
        squares(n-1,length/2)
        turtle.pu()
        turtle.forward(length)
        turtle.pd()
        squares(n-1,length/2)
        turtle.left(135)
        turtle.forward(length*math.sqrt(2))
        turtle.right(135)
        squares(n-1,length/2)
        turtle.right(45)
        turtle.forward(length*math.sqrt(2)/2)
        turtle.left(45)
        
squares(n)
turtle.done()
